version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
	    - '443:443'
	    - '6666:6666'
	    - '7777:7777'
    links:
	   - nexus
	volumes:
	   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./nginx/ssl:/etc/nginx/ssl:ro
    command: [ nginx, '-g', 'daemon off;' ]
  nexus:
    image: docker.io/sonatype/nexus3:3.42.0
    volumes:
     - '~/nexus-data:/nexus-data'

volumes:
  nexus3-data:
