version: '3'

services:
  nginx-nexusproxy:
    image: nginx-nexusproxy
    ports:
      - '443:443'
      - '6666:6666'
      - '7777:7777'
    links:
      - nexus-repo
    command: [ nginx, '-g', 'daemon off;' ]

  nexus-repo:
    image: docker.io/sonatype/nexus3:3.41.1
    volumes:
      - '/nexus-data:/nexus-data'

volumes:
  nexus3-data:
