version: '3.9'

services:
  nginx:
    image: nginx:alpine
    command: [ nginx, '-g', 'daemon off;' ]
    ports:
     - '443:443'
     - '6666:6666'
     - '7777:7777'
    links:
     - nexus
    volumes:
     - /root/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - /root/nginx/ssl:/etc/nginx/ssl:ro
  nexus:
    image: docker.io/sonatype/nexus3:3.42.0
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 3G
    volumes:
     - 'nexus-data:/nexus-data'
volumes:
  nexus-data:
