version: '3'

services:
  squid:
    image: ubuntu/squid:5.2-22.04_beta
    ports:
      - '3128:3128'
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro
      - /var/log/squid:/var/log/squid
      - /srv/docker/squid/cache:/var/spool/squid
